-- Tasko Packages Module schema + sample seed data
-- SQL dialect: PostgreSQL

CREATE TABLE IF NOT EXISTS packages (
  package_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_name VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
  duration_days INTEGER NOT NULL CHECK (duration_days > 0),
  visit_frequency VARCHAR(24) NOT NULL CHECK (visit_frequency IN ('daily', 'weekly', 'every_2_days', 'monthly')),
  status BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS package_services (
  package_service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id BIGINT NOT NULL REFERENCES packages(package_id) ON DELETE CASCADE,
  category_name VARCHAR(120) NOT NULL,
  sub_category_name VARCHAR(120) NOT NULL,
  service_frequency VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_packages (
  user_package_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  package_id BIGINT NOT NULL REFERENCES packages(package_id) ON DELETE RESTRICT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR(24) NOT NULL CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS package_schedule (
  schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_package_id BIGINT NOT NULL REFERENCES user_packages(user_package_id) ON DELETE CASCADE,
  service_date DATE NOT NULL,
  worker_id BIGINT,
  status VARCHAR(24) NOT NULL CHECK (status IN ('pending', 'assigned', 'completed'))
);

CREATE TABLE IF NOT EXISTS package_payments (
  payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_package_id BIGINT NOT NULL REFERENCES user_packages(user_package_id) ON DELETE CASCADE,
  amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
  payment_method VARCHAR(60) NOT NULL,
  payment_status VARCHAR(40) NOT NULL,
  paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS package_services_unique_entry
  ON package_services(package_id, category_name, sub_category_name, service_frequency);

INSERT INTO packages (package_id, package_name, description, price, duration_days, visit_frequency, status, created_at)
VALUES
  (1, 'Basic Home Care', 'Daily home support package for essential household chores.', 999, 30, 'daily', TRUE, NOW()),
  (2, 'Weekly Deep Cleaning', 'Focused deep cleaning package for bathrooms, kitchens and windows.', 499, 7, 'weekly', TRUE, NOW()),
  (3, 'Vehicle Care Package', 'Recurring vehicle wash package for bikes and cars.', 799, 30, 'every_2_days', TRUE, NOW()),
  (4, 'Beauty & Grooming', 'At-home grooming essentials for monthly personal care.', 999, 30, 'monthly', TRUE, NOW()),
  (5, 'Garden Maintenance', 'Weekly garden support for healthy lawn and plants.', 699, 30, 'weekly', TRUE, NOW())
ON CONFLICT (package_id) DO UPDATE
SET
  package_name = EXCLUDED.package_name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  duration_days = EXCLUDED.duration_days,
  visit_frequency = EXCLUDED.visit_frequency,
  status = EXCLUDED.status;

SELECT setval(
  pg_get_serial_sequence('packages', 'package_id'),
  GREATEST((SELECT COALESCE(MAX(package_id), 1) FROM packages), 1),
  TRUE
);

INSERT INTO package_services (package_id, category_name, sub_category_name, service_frequency)
VALUES
  (1, 'Home Care', 'Floor Cleaning', 'daily'),
  (1, 'Home Care', 'Dish Washing', 'daily'),
  (1, 'Home Care', 'Trash Cleaning', 'daily'),
  (2, 'Deep Cleaning', 'Bathroom Cleaning', 'weekly'),
  (2, 'Deep Cleaning', 'Kitchen Cleaning', 'weekly'),
  (2, 'Deep Cleaning', 'Window Cleaning', 'weekly'),
  (3, 'Vehicle Care', 'Bike Wash', 'every_2_days'),
  (3, 'Vehicle Care', 'Car Wash', 'every_2_days'),
  (4, 'Beauty & Grooming', 'Haircut', 'monthly'),
  (4, 'Beauty & Grooming', 'Beard Trim', 'monthly'),
  (4, 'Beauty & Grooming', 'Facial', 'monthly'),
  (5, 'Garden Maintenance', 'Grass Cutting', 'weekly'),
  (5, 'Garden Maintenance', 'Plant Watering', 'weekly')
ON CONFLICT (package_id, category_name, sub_category_name, service_frequency) DO NOTHING;
